title: Kevin Patrick O'Brien
email: your-email@example.com
description: Data science and R programming blog.
baseurl: "" 
url: "https://kobriendublin.github.io"
theme: minima

# Define your navigation menu here
header_pages:
  - about.md
  - portfolio.md
  - R_community.md
  - FAQ.md